/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class MemoriEngine {
  constructor(modelName: string | undefined | null, fetchEmbeddingsCb: (id: number, reqJson: string) => void, fetchFactsByIdsCb: (id: number, reqJson: string) => void, writeBatchCb: (id: number, reqJson: string) => void)
  resolveCallback(id: number, result: string): void
  embedTexts(texts: Array<string>): Array<Float32Array>
  retrieve(requestJson: string): Promise<string>
  recall(requestJson: string): Promise<string>
  submitAugmentation(inputJson: string): string
  waitForAugmentation(timeoutMs?: number | undefined | null): Promise<boolean>
}
