/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class MemoriEngine {
  constructor(modelName: string | undefined | null, fetchEmbeddingsCb: (...args: any[]) => any, fetchFactsByIdsCb: (...args: any[]) => any, writeBatchCb: (...args: any[]) => any)
  retrieve(requestJson: string): Promise<string>
  recall(requestJson: string): Promise<string>
  waitForAugmentation(timeoutMs?: number | undefined | null): Promise<boolean>
  submitAugmentation(inputJson: string): string
  embedTexts(textsJson: string): string
  execute(command: string): string
  helloWorld(): string
}
